data: 

  - city: BAB
    frequency: 5
    browser: chrome
    ratio_max: 11000
    urls: 
      seloger: "https://www.seloger.com/list.htm?types=1%2C2&projects=2&enterprise=0&sort=d_dt_crea&natures=1%2C4&surface=10%2FNaN&places=%5B%7Bci%3A640122%7D%7C%7Bci%3A640024%7D%7C%7Bci%3A640102%7D%7C%7Bci%3A640125%7D%5D&qsVersion=1.0"
      pap: "https://www.pap.fr/annonce/vente-appartement-maison-bayonne-64100-g33230g33376g33377g33708"
      # leboncoin: "https://www.leboncoin.fr/recherche/?category=9&locations=Bayonne_64100,Anglet_64600,Biarritz_64200,Bidart_64210&real_estate_type=1,2,3,5"
 
