# https://medium.freecodecamp.org/a-recipe-for-website-automated-tests-with-python-selenium-headless-chrome-in-docker-8d344a97afb5

# usage: docker-compose up
# open browser at localhost:600

# monitoring
# docker stats housingpricemonitor_web_1 housingpricemonitor_worker_1 housingpricemonitor_mongo_1
# see internal ip addresses
# docker inspect housingpricemonitor_worker_1

# https://stackoverflow.com/questions/27937185/assign-static-ip-to-docker-container
# avant network
# "Gateway": "172.18.0.1",
# "IPAddress": "172.18.0.3",
# apres network
# "Gateway": "172.20.5.0",
# "IPAddress": "172.20.128.2",

version: '2'

services:

  test_worker:
    build: . 
    volumes:
      - ./:/usr/workspace/
    command: python test_worker.py  # TODO: use nosetests instead
    environment:
      - PYTHONUNBUFFERED=1

  worker:
    depends_on:
      - test_worker
    restart: always
    build: . 
    volumes:
      - ./:/usr/workspace/
    command: python worker.py
    environment:
      - PYTHONUNBUFFERED=1
    # networks:
    #   static-network:
    #     ipv4_address: 172.20.128.2  # internal ip address of container (static)

  web:
    restart: always
    depends_on:
      - worker
    build: . 
    volumes:
      - ./:/usr/workspace/
    ports:
      - '600:5000'
    command: python run_app.py
    environment:
      - PYTHONUNBUFFERED=1

  mongodb:
    restart: always
    image: mongo:3.4.6
    # disable logger
    logging:
      driver: none

# networks:
#   static-network:
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16
#           ip_range: 172.28.5.0/24
