# https://medium.freecodecamp.org/a-recipe-for-website-automated-tests-with-python-selenium-headless-chrome-in-docker-8d344a97afb5

# usage: docker-compose up
# open browser at localhost:8000

# monitoring
# docker stats housingpricemonitor_web_1 housingpricemonitor_worker_1 housingpricemonitor_mongo_1

version: '2'

services:

  worker:
    restart: always
    build: . 
    volumes:
      - ./:/usr/workspace/
    command: python worker.py --city=paris
    environment:
      - PYTHONUNBUFFERED=1

  web:
    restart: always
    depends_on:
      - worker
    build: . 
    volumes:
      - ./:/usr/workspace/
    ports:
      - '8000:5000'
    command: python run_app.py
    environment:
      - PYTHONUNBUFFERED=1

  mongodb:
    restart: always
    image: mongo:3.4.6
